### ISSUE TITLE
`isFirebugInstalled()`

### ISSUE THREAD

**Issue by cadorn** [firebug/firebug.sdk#1]
Does it make sense to have an `isFirebugInstalled()` method?

Still trying to wrap my head around where this SDK fits in as compared to firebug.next extension.

**Comment by cadorn** [comment]
$feature https://github.com/firephp/firephp-for-firebug.next/issues/1

**Comment by janodvarko** [comment]
> Does it make sense to have an isFirebugInstalled() method?

Yes

> Still trying to wrap my head around where this SDK fits in as compared to firebug.next extension.

It's fresh new and I need some time yet. For now I took code from Pixel Perfect and I'll continue porting code from Firebug.next (mostly the concept of overlays == existing panel and toolbox customisation)
For now, I can image that it isn't ready for other extensions yet. I'll be posting to the FWG newsgroups as I am doing more progress...

Honza

**Comment by janodvarko** [comment]
Two new APIs:
System.isFirebugInstalled()
System.getFirebugVersion()

Introduced in 0.5.2 (published on npmjs.org)

Honza
