### ISSUE TITLE
Reps: falsy values are displayed as empty string

### ISSUE THREAD

**Issue by jsnajdr** [firebug/firebug.sdk#19]
When displaying a falsy value using the TreeView from Reps, it's always displayed as empty string `""`, even if it is `undefined`, `false`, `0` etc.

I discovered this when using the WebSocket monitor addon. When it displays the WebSocket frames, the values of things like `finBit` or `opCode` are displayed incorrectly, which is very confusing.

**Comment by janodvarko** [comment]
PR merged.

Honza
